{% set version = "23.0.0" %}

package:
  name: pyopenssl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyOpenSSL/pyOpenSSL-{{ version }}.tar.gz
  sha256: c1cc5f86bcacefc84dada7d31175cae1b1518d5f60d3d0bb595a67822a868a6f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cryptography >=38.0.0,<40

test:
  source_files:
    - tests/*
  commands:
    - pytest tests
  requires:
    - pytest
    - flaky
    - pretend
  imports:
    - OpenSSL
    - OpenSSL.crypto
    - OpenSSL.rand
    - OpenSSL.SSL

about:
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
  description: |
    pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.
    It includes:
    -SSL.Connection objects, wrapping the methods of Python's portable sockets
    -Callbacks written in Python
    -Extensive error-handling mechanism, mirroring OpenSSL's error codes
    and much more.
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
  dev_url: https://github.com/pyca/pyopenssl

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
